---
output: html_document
---

## Purpose
This shiny dashboard explores data on **National Football League (NFL)** games from 2006 to 2020 and fits three statistical models to predict the total score of games. The models can then be used, along with user input of predictor values, to predict the total score of a particular game. The [data](http://www.habitatring.com/games.csv) provides information about each game like identifcation parameters, game conditions, game results, and pregame lines (expected results of the game scores) with corresponding odds. For more information about the dataset and a data dictionary of the column variables visit [NFL Game data information](https://github.com/nflverse/nfldata/blob/master/DATASETS.md#games).

## Data Tab
The data tab allows the user to explore the dataset with options to filter the data by columns or rows. The column filter will filter the dataset by the selected variables. The rows of the dataset can be filtered by the season the game was played, the game type, and the teams that played in the game. The filters may be used together to really examine the data. The dataset can be saved by clicking the "Save Data" dropdown in the upper right of the "Data" box. The saved file can be named and then is saved as a csv with the "Save Data" button. If no name is entered, the csv file will be titled "NFL Games Data.csv".

## Data Exploration Tab
The data exploration tab allows the user to conduct an exploratory data analysis (EDA) of the data. The tab is broken into two sections, one for contingency and summary tables, the other for creating visuals. The contingency table displays the number of games for the selected input variable. The user may create a two dimensional contigency table by clicking the "Add variable" switch and selecting their desired variable. A summary table that displays the five number summary along with the mean and standard deviation can be generated for some of the continuous variables in the dataset. These summaries of the different variables can be compared by selecting multiple variables in the dropdown menu.

The visuals section of this tab allows the user to create 

## Modeling Tabs
### Modeling Info Tab

### Model Fitting Tab

### Prediction Tab
